/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Booking.model.roomList'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 1,
                name: 'Verdana Room'
            },
            {
                id: 2,
                name: 'Arial Room'
            },
            {
                id: 3,
                name: 'Georgia Room'
            },
            {
                id: 4,
                name: 'Helvetica Room'
            }
        ],
        model: 'Booking.model.roomList',
        storeId: 'MyStore'
    }
});