/*
 * File: app/view/mainCarousel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.view.mainCarousel', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.mainCarousel',

    requires: [
        'Booking.view.MyContainer1',
        'Booking.view.MyContainer2'
    ],

    config: {
        fullscreen: true,
        ui: 'light',
        direction: 'vertical',
        items: [
            {
                xtype: 'MyContainer1'
            },
            {
                xtype: 'MyContainer2'
            }
        ],
        listeners: [
            {
                fn: 'onCarouselShow',
                event: 'show'
            }
        ]
    },

    onCarouselShow: function(component, eOpts) {
        var token = Booking.app.authToken;
        gapi.auth.setToken(token);
        gapi.client.load('calendar', 'v3', function() {
            var request = gapi.client.calendar.events.list({
                'calendarId': 'primary'
            });

            request.execute(function(resp) {
                for (var i = 0; i < resp.items.length; i++) {
                    console.log(resp.items[i].summary);
                }
            });
        });
    }

});