/*
 * File: app/view/myCanvas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.view.myCanvas', {
    extend: 'Ext.Component',
    alias: 'widget.myCanvas',

    config: {
    },

    initialize: function() {
        this.canvas.on({
            tap: 'onTap',
            touchstart: 'onTouchStart',
            touchend: 'onTouchEnd',
            touchmove: 'onTouchMove',
            scope: this
        });
    },

    onTap: function(e) {
        this.fireEvent('tap',this,e);
    },

    onTouchStart: function(e) {
        this.fireEvent('touchstart',this,e);
    },

    onTouchEnd: function(e) {
        this.fireEvent('touchend',this,e);
    },

    onTouchMove: function(e) {
        this.fireEvent('touchmove',this,e);
    }

});