/*
 * File: app/view/MyPanel1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.view.MyPanel1', {
    extend: 'Ext.Panel',

    config: {
        height: '100%',
        html: '<canvas id="mycanvas" width="500px" height="500px"></canvas>',
        width: '100%',
        listeners: [
            {
                fn: 'onPanelInitialize',
                event: 'initialize'
            }
        ]
    },

    onPanelInitialize: function(component, eOpts) {
        var canvas = document.getElementById('mycanvas');        
        var context = canvas.getContext("2d");
        var cw = canvas.width;
        var ch = canvas.height;
        context.strokeStyle = 'black';
        context.moveTo(0,0);
        context.lineTo(cw,ch);
        context.stroke();
        context.fillRect(25,25,100,100);
        context.clearRect(45,45,60,60);
        context.strokeRect(50,50,50,50);
    }

});